<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>14</LangVersion>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
    <AssemblyName>PS5Suite</AssemblyName>
    <RootNamespace>PS5Upload</RootNamespace>
    <ApplicationIcon>ps5_logo.ico</ApplicationIcon>
    <Version>7.3.0</Version>
    <Authors>Manos</Authors>
    <Description>PS5 Suite - Complete PS5 Management Platform</Description>
    <Copyright>Copyright © 2026 Manos</Copyright>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="ps5_logo.ico" />
    <AvaloniaResource Include="ps5_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.3" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.3" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.2" />
    <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="Avalonia.Diagnostics" Version="11.3.22" />
    <PackageReference Include="SMBLibrary" Version="1.5.8.1" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
    <Reference Include="LibProsperoPkg">
      <HintPath>libs\LibProsperoPkg.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
