<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-android</TargetFramework>
    <SupportedOSPlatformVersion>23</SupportedOSPlatformVersion>
    <Nullable>enable</Nullable>
    <ApplicationId>com.manos.ps5suite</ApplicationId>
    <ApplicationVersion>9</ApplicationVersion>
    <ApplicationDisplayVersion>7.3.0</ApplicationDisplayVersion>
    <ApplicationTitle>PS5 Suite</ApplicationTitle>
    <AndroidPackageFormat>apk</AndroidPackageFormat>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
  </PropertyGroup>

  <ItemGroup>
    <AndroidResource Include="Resources\drawable\icon.jpg" />
    <AndroidResource Include="Resources\drawable\splash_screen.xml" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Android" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PS5SuiteAndroid\PS5SuiteAndroid.csproj" />
  </ItemGroup>
</Project>
